### PR TITLE
Only call alerts js when necessary

### PR DESCRIPTION
**Pull request by froboy**
Backport patch from YMCA Dayton and reapply recent patches.

To test:
- clear caches, ensure js aggregation is off 
- with no alerts published, observe `main.js` is not loaded
- publish an alert (maybe clear caches?), observe `main.js` is loaded and the alert is properly displayed.

### CODE REVIEW

**Comment by froboy** [comment]
@podarok for your review when you have a moment.

**Review by podarok — APPROVED** [review]

**Comment by AndreyMaximov** [comment]
@froboy @podarok Does this change imply that Alerts can be visible only on node pages, not anywhere else?

I mean, if there is a page generated by a taxonomy term or a views-based page it won't show up the alerts?

**Comment by froboy** [comment]
@AndreyMaximov i think that was the case even before this patch, as the library was added in the node preprocess, just for all nodes instead of only where it was needed. If alerts are needed other places that would probably be new (but not too hard) functionality.

**Comment by froboy** [comment]
@podarok can you confirm that they worked that way before though? Just looking at the code it looks like they only loaded on nodes before this change too.

**Comment by AndreyMaximov** [comment]
image
The hook comment is misleading. The actual hook is still `hook_preprocess_page()` - any page rendering process invokes it.

**Comment by froboy** [comment]
@AndreyMaximov oops! That's what I get for looking at this comment on my phone first thing in the morning. Ok, I'll check in with the team and understand what the process is to make the change with the new structure. @podarok do you know if there's a new board yet or where new work should go?

**Comment by podarok** [comment]
https://dev.azure.com/y-usa/Open%20Y%20Product%20Development/_workitems/edit/31498/

**Comment by froboy** [comment]
@AndreyMaximov @podarok sorry for the delay, but I'm re-reviewing this now. Andrey, to your concerns, it seems that the module is already invalidating cache tags for all of the newly affected entities. 

https://github.com/open-y-subprojects/openy_node_alert/blob/main/openy_node_alert.module#L73-L75

I believe that should take care of adding the JS if it's not there already, correct?

**Comment by podarok** [comment]
This was a mistake to commit.

We'll be reverting it
Completely breaking functionality of alerts when new alert added to the page - only full Drupal cache clean could fix the issue

**Pull request merged**
