### PR TITLE
Change the alerts description length calculation logic

### PR DESCRIPTION
**Pull request by LeonidImagex**

### CODE REVIEW

**Comment by podarok** [comment]
What is the issue are you trying to solve @LeonidImagex ?

**Comment by froboy** [comment]
I got some context from Leonid... 

> I have faced and issue with the openy_node_alter module and I have added some changes to the description of the alters length calculation

for context I have the description like this:

```
<p>The County Y will remain closed through July 6.&nbsp;We will reopen the below amenities on Friday, July 7, for adjusted hours (see below.)&nbsp;&nbsp;<br />
<br />
<strong>Friday 5am - 7pm<br />
Saturday 7am - 5pm<br />
Sunday noon - 5pm<br />
Monday - normal hours will resume!</strong></p>

<ul>
	<li>Pool and water fitness classes; check mobile app for schedule</li>
	<li>Group Swim lessons will resume.</li>
	<li>Private swim lessons should connect with your instructor!</li>
	<li>All fitness and cardio equipment (relocated to the gymnasium)</li>
	<li>Mens/Womens/Universal locker rooms</li>
	<li>New temporary personal fitness area located in first floor community room</li>
</ul>
```
> and the forEach failed for me, I have added simple tag stripping and counting of the symbols

**Comment by froboy** [comment]
I've tested this. The issue is that the current logic (from https://github.com/open-y-subprojects/openy_node_alert/pull/138) tries to loop over many different types of HTML objects with a relatively inflexible logic (not sure which SO post I found that on, but it wasn't good). 

@LeonidImagex's fix is more simple, uses an existing native function, and most importantly, works. :) 

I approve this.

**Comment by LeonidImagex** [comment]
@froboy thanks for the context. I also want to mention that I encountered an error that broke the entire page on this line:
`else length += el.props.children.length;`
I don't have the precise error text, but the issue was that not all `el.props` have `children`, and as a result, we can't call the `length` method on them.

**Pull request merged**
